services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    webServerPort: 10000
    envVars:
      - key: BOT_TOKEN
        value: your-bot-token-here
      - key: WEBHOOK_URL
        value: https://your-app.onrender.com