services:
  - type: web
    name: smart-notator-bot
    env: python
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    plan: free